service:
  name: serverless-typescript-template

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.ts'

functions:
  authorizer:
    handler: functions/authorizer.default
  index:
    handler: functions/handler.default
    events:
      - http:
          method: get
          path: /
          authorizer: authorizer
