service:
  name: aws-nodejs-typescript

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.ts'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  api:
    handler: api.api
    events:
      - http:
          method: get
          path: api
